### ISSUE TITLE
Error metric and datasets

### ISSUE THREAD

**Issue by pasqualecoscia** [SZamboni/Social_lstm_pedestrian_prediction#3]
Hi! I have two questions about your code:
1. In your report you say that you need to multiply the error (ADE) obtained using the function get_mean_error() by the value 15 to denormalize it and obtain the error in meters. Why did you use such value? In your code you did not use such constant.
2. Did you use some kind of normalization for your datasets? They look different from the ones uploaded in other github repositories.

Thanks!

**Comment by SZamboni** [comment]
Hi, regarding the two questions they are both correlated. The PhD supervising me in this project normalized the data and did some transformation and then give the data to me. I think he told me to not multiply by 15 in the code because he said it was not necessary, but I do not remember correctly.

Unfortunately, I cannot answer questions regarding the data since I was not the person processing them, I used them as they were given to me since that part was not in the scope of my project.
